### ISSUE TITLE
PluginPreview: MIDI playback test (kicked by "MIDI" button) often causes app crash

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/aap-core#146]
This crash often happens. It is more like Android MIDI API client side of the stack trace though.

```
00:27:53.049 27231-27265 AndroidRuntime  org...strumentsample  E  FATAL EXCEPTION: DefaultDispatcher-worker-2
                                                                  Process: org.androidaudioplugin.aapinstrumentsample, PID: 27231
                                                                  java.io.IOException: write failed: EPIPE (Broken pipe)
                                                                  	at libcore.io.IoBridge.write(IoBridge.java:651)
                                                                  	at java.io.FileOutputStream.write(FileOutputStream.java:401)
                                                                  	at android.media.midi.MidiInputPort.onSend(MidiInputPort.java:89)
                                                                  	at android.media.midi.MidiReceiver.send(MidiReceiver.java:128)
                                                                  	at android.media.midi.MidiReceiver.send(MidiReceiver.java:105)
                                                                  	at org.androidaudioplugin.samples.host.engine.PluginPreview.doPlayMidiNotes(PluginPreview.kt:508)
                                                                  	at org.androidaudioplugin.samples.host.engine.PluginPreview.access$doPlayMidiNotes(PluginPreview.kt:23)
                                                                  	at org.androidaudioplugin.samples.host.engine.PluginPreview$doPlayMidiNotes$1.invokeSuspend(Unknown Source:14)
                                                                  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                                                                  	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3f9df60, Dispatchers.Default]
                                                                  Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
                                                                  	at libcore.io.Linux.writeBytes(Native Method)
                                                                  	at libcore.io.Linux.write(Linux.java:296)
                                                                  	at libcore.io.ForwardingOs.write(ForwardingOs.java:943)
                                                                  	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:448)
                                                                  	at libcore.io.ForwardingOs.write(ForwardingOs.java:943)
                                                                  	at libcore.io.IoBridge.write(IoBridge.java:646)
                                                                  	... 13 more
```

**Comment by atsushieno** [comment]
Since this never happens when we use kmmk, it is more likely a bug in PluginPreview client side.

**Comment by atsushieno** [comment]
at bb9c8eb I have added very primitive crash protector. I still didn't find the actual crasher yet.

**Comment by atsushieno** [comment]
We have replaced `PluginPreview` in androidaudioplugin-ui-compose with the fresh implementation (androidaudioplugin-ui-compose-app). Therefore, this issue becomes obsoleted.
